/**
 * claude.ts — Template-based drop-in replacement
 *
 * All function signatures are identical to the original so that
 * no other file in the project needs to change.
 *
 * The Anthropic SDK has been removed entirely.
 * Content is generated by templates.ts using the user's actual quiz data.
 */

import {
  generateMicroInsightTemplate,
  selectAdaptiveQuestionsTemplate,
  generateReportTemplate,
  generateStreamingText,
  generateDimensionDeepDiveTemplate,
  type AnswerRecord,
  type DimensionData,
} from "./templates";

/* ── Micro-insight ────────────────────────────────────────── */
export async function generateMicroInsight(
  age: number,
  answers: AnswerRecord,
  triggerQuestion: string
): Promise<string> {
  return generateMicroInsightTemplate(age, answers, triggerQuestion);
}

/* ── Adaptive question selection ─────────────────────────── */
export async function selectAdaptiveQuestions(
  symptoms: string[],
  availableQuestionIds: string[]
): Promise<string[]> {
  return selectAdaptiveQuestionsTemplate(symptoms, availableQuestionIds);
}

/* ── Report generation ────────────────────────────────────── */
export async function generateReport(
  answers: AnswerRecord,
  dimensions: DimensionData[],
  wellnessScore: number,
  biologicalAge: number,
  chronologicalAge: number,
  primaryTreatment: string,
  supportingTreatments: string[]
) {
  return generateReportTemplate(
    answers,
    dimensions,
    wellnessScore,
    biologicalAge,
    chronologicalAge,
    primaryTreatment,
    supportingTreatments
  );
}

/* ── Streaming analysis (fake stream, same format) ────────── */

type StreamEvent = {
  type: string;
  delta?: { type: string; text: string };
  index?: number;
};

export async function streamAnalysis(
  answers: AnswerRecord,
  dimensions: DimensionData[],
  wellnessScore: number,
  biologicalAge: number,
  chronologicalAge: number,
  primaryTreatment: string,
  supportingTreatments: string[]
): Promise<AsyncIterable<StreamEvent>> {
  const fullText = generateStreamingText(
    answers,
    dimensions,
    wellnessScore,
    biologicalAge,
    chronologicalAge,
    primaryTreatment,
    supportingTreatments
  );

  async function* fakeStream(): AsyncGenerator<StreamEvent> {
    // Send in small chunks to simulate real streaming
    const CHUNK_SIZE = 6;
    for (let i = 0; i < fullText.length; i += CHUNK_SIZE) {
      yield {
        type: "content_block_delta",
        delta: { type: "text_delta", text: fullText.slice(i, i + CHUNK_SIZE) },
        index: 0,
      };
      // ~12 ms per chunk ≈ 500 chars/sec — feels live without being slow
      await new Promise((r) => setTimeout(r, 12));
    }
  }

  return fakeStream();
}

/* ── Chat response (scripted, since widget is not live) ────── */
export async function chatResponse(
  messages: Array<{ role: "user" | "assistant"; content: string }>,
  context: {
    answers: AnswerRecord;
    wellnessScore: number;
    biologicalAge: number;
    treatments: string[];
  },
  messageCount = 0
): Promise<string> {
  const lastUser = [...messages]
    .reverse()
    .find((m) => m.role === "user")
    ?.content?.toLowerCase() ?? "";

  const primary = context.treatments[0] ?? "NAD+ IV Drip";
  const bookingLink =
    "https://link.harleystreetmedicalwellness.co.uk/widget/bookings/wellness-consultant-1";

  if (lastUser.includes("price") || lastUser.includes("cost") || lastUser.includes("expensive")) {
    return `Great question on pricing. ${primary} delivers nutrients at 100% bioavailability directly to your cells — compared to 5–15% from oral supplements. Many clients find they reduce or eliminate 3–4 monthly supplements after starting IV therapy, which offsets a significant portion of the cost. The best way to discuss the right plan for your budget is through a <strong>free, no-obligation consultation</strong>. <a href="${bookingLink}">Book here</a> — takes 2 minutes.`;
  }

  if (lastUser.includes("safe") || lastUser.includes("side effect") || lastUser.includes("risk")) {
    return `IV vitamin therapy has an excellent safety record. ${primary} is administered by GMC-registered doctors at our Harley Street clinic. Side effects are rare and typically limited to mild warmth or a slight taste sensation during infusion. You sit comfortably throughout, can work on your laptop, and leave immediately after. Our clinical team monitors you throughout the entire session.`;
  }

  if (lastUser.includes("book") || lastUser.includes("appointment") || lastUser.includes("consultation")) {
    return `You can book your <strong>free, no-obligation consultation</strong> directly here: <a href="${bookingLink}">Book a free slot</a>. Available at both our London (Harley Street) and Glasgow clinics. Our clinical team will review your full quiz results and create a personalised treatment plan.`;
  }

  if (lastUser.includes("how long") || lastUser.includes("how quickly") || lastUser.includes("results")) {
    return `Most clients with a wellness score of ${context.wellnessScore}/100 notice improvements within the first 24–48 hours after ${primary} — particularly in energy levels. Cognitive and sleep improvements typically follow over weeks 1–2. For the most accurate timeline specific to your profile, a <strong>free consultation</strong> with our clinical team is the best next step: <a href="${bookingLink}">book here</a>.`;
  }

  if (lastUser.includes("supplement") || lastUser.includes("vitamin") || lastUser.includes("pill")) {
    return `Oral supplements deliver approximately 5–15% of their active compounds to your cells — the rest is largely destroyed by digestion. ${primary} delivered intravenously achieves ~100% cellular bioavailability, producing therapeutic concentrations that oral supplementation simply cannot replicate. That's why clients with your profile see results so quickly — your cells are actually receiving the full dose.`;
  }

  // Escalation-tier defaults
  if (messageCount <= 5) {
    return `Based on your wellness score of ${context.wellnessScore}/100 and biological age of ${context.biologicalAge}, ${primary} is specifically recommended to address your primary cellular health opportunities. What aspects of the treatment or your results would you like me to explain further?`;
  }
  if (messageCount <= 12) {
    return `Given everything we've discussed about your profile, a <strong>free consultation</strong> with our clinical team is the ideal next step — they can map out a personalised protocol based on your quiz results and answer any remaining questions in person. Completely no-obligation. <a href="${bookingLink}">Book your free slot here</a>.`;
  }
  return `I'd love to connect you with our clinical team who can build a fully personalised longevity protocol for you. Book a <strong>free, no-obligation consultation</strong> here: <a href="${bookingLink}">Book now</a>.`;
}

/* ── Dimension deep dive ─────────────────────────────────── */
export async function generateDimensionDeepDive(
  dimensionName: string,
  score: number,
  answers: AnswerRecord,
  biologicalAge: number,
  recommendedTreatment: string
) {
  return generateDimensionDeepDiveTemplate(
    dimensionName,
    score,
    answers,
    biologicalAge,
    recommendedTreatment
  );
}
